using UnityEngine;
using UnityEngine.Events;

namespace Toolkits.Loading
{
    /// <summary>
    /// A component that allows for load task events to be assigned in the inspector.
    /// </summary>
    [AddComponentMenu("Toolkits/Loading/Load Task Event Listener")]
    public class LoadTaskEventListener : MonoBehaviour
    {
        /// <summary>
        /// The channel to listen to events from.
        /// </summary>
        [Tooltip("The channel to listen to events from.")]
        [SerializeField] private LoadTaskEventChannelSO _channel = null;

        /// <summary>
        /// The <see cref="UnityEvent"/> to invoke when an event is raised in the channel.
        /// </summary>
        [Tooltip("The UnityEvent to invoke when an event is raised in the channel.")]
        [SerializeField] private UnityEvent<ILoadTask, float> _onRaised = null;

        /// <summary>
        /// Start listening to the event channel when the script is enabled.
        /// </summary>
        private void OnEnable()
        {
            if (_channel) _channel.OnRaised += Raise;
        }

        /// <summary>
        /// Stop listening to the event channel when the script is disabled.
        /// </summary>
        private void OnDisable()
        {
            if (_channel) _channel.OnRaised -= Raise;
        }

        /// <summary>
        /// Raises the Unity event from the inspector.
        /// </summary>
        private void Raise(ILoadTask loadTask, float progress) => _onRaised?.Invoke(loadTask, progress);
    }
}
